["~/.config/nvim"]
type = "git-repo"
url = "https://github.com/jacobng/nvim.git"
# refreshPeriod determines how often chezmoi pulls updates automatically
refreshPeriod = "168h"  # refresh every 7 days
